export 'package:jaep_movies_app/presentation/widgets/movies/movie_masonry.dart';
export 'package:jaep_movies_app/presentation/widgets/shared/custom_bottom_navigation.dart';
export 'package:jaep_movies_app/presentation/widgets/movies/videos_from_movie.dart';
export 'package:jaep_movies_app/presentation/widgets/actors/actors_by_movie.dart';
export 'package:jaep_movies_app/presentation/widgets/movies/movie_genres.dart';
export 'package:jaep_movies_app/presentation/widgets/movies/movie_horizontal_listview.dart';
export 'package:jaep_movies_app/presentation/widgets/movies/movie_rating.dart';
export 'package:jaep_movies_app/presentation/widgets/movies/movies_slideshow.dart';
export 'package:jaep_movies_app/presentation/widgets/shared/custom_appbar.dart';
